examples/TwoLogFilesMvc/Controllers/LoggingDemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.IO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;


namespace TwoLogFilesMvc {
	
	public class LoggingDemoController : Controller {

		ILogger<LoggingDemoController> Logger;

		public LoggingDemoController(ILogger<LoggingDemoController> logger) {
			Logger = logger;
		}

		public IActionResult DemoPage() {
			return View();
		}

		public IActionResult LogMessage(string logLevel, string msg) {
			Logger.Log( (LogLevel)Enum.Parse(typeof(LogLevel), logLevel, true), msg);
			return Ok();
		}

	}
}

examples/TwoLogFilesMvc/Views/LoggingDemo/DemoPage.cshtml
@model System.Collections.IDictionary
	
<h1>
	NReco.File.Logging demo
	<small style="color:silver;">lightweight logging to files</small>
</h1>

<form action="@Url.Action("LogMessage", "LoggingDemo")" target="submitResult" method="post">

	<table border="0">
		<tr>
			<th>LogLevel</th>
			<td>
				<select name="logLevel">
					<option value="Debug">Debug</option>
					<option value="Information">Information</option>
					<option value="Warning">Warning</option>
				</select>
			</td>
		</tr>
		<tr>
			<th>Message</th>
			<td><input type="text" name="msg" value="This is a log message!"/></td>
		</tr>
	</table>

	<button type="submit">Add</button>
</form>

<iframe name="submitResult" style="display:none;"></iframe>

examples/TwoLogFilesMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta charset="utf-8" />
        <title>NReco.Logging.File Demo</title>
        
		<meta http-equiv="X-UA-Compatible" content="IE=edge"/>

        <style>
            body {
                font-family:Arial;
            }
        </style>

    </head>
    <body>	

		<div class="container">
			@RenderBody()
			<hr/>
		</div>

        @RenderSection("scripts", required: false)
    </body>
</html>